name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GTK4
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev

      - name: Build
        run: cargo build --release --verbose

      - name: Test
        run: cargo test --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lil-miss-wheats-linux
          path: target/release/lil-miss-wheats

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cargo

      - name: Build
        run: cargo build --release --verbose
        env:
          GSETTINGS_SCHEMA_DIR: C:/msys64/mingw64/share/glib-2.0/schemas

      - name: Test
        run: cargo test --verbose
        env:
          GSETTINGS_SCHEMA_DIR: C:/msys64/mingw64/share/glib-2.0/schemas

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lil-miss-wheats-windows
          path: target/release/lil-miss-wheats.exe
